namespace Youtube_Music.Forms
{
    partial class MainForm
    {
<<<<<<< HEAD:src/Forms/MainForm.Designer.cs
       
        private System.ComponentModel.IContainer components = null;

       
=======
        /// <summary>
        /// Required design variable
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up used resources
        /// </summary>
        /// <param name="disposing">True, if managed resources are to be deleted; otherwise False.</param>
>>>>>>> 2a6c1532dfa2c5ff5b3554f0396922eaa4887546:src/MainForm.Designer.cs
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

<<<<<<< HEAD:src/Forms/MainForm.Designer.cs
        #region Designer Code

=======
        #region Code generated by the Windows Form Designer

        /// <summary>
        /// Required code to support the design
        /// The content of this method cannot be changed using the code editor
        /// </summary>
>>>>>>> 2a6c1532dfa2c5ff5b3554f0396922eaa4887546:src/MainForm.Designer.cs
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.volumeTrackBar = new System.Windows.Forms.TrackBar();
            this.SettingsBtn = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.volumeTrackBar)).BeginInit();
            this.SuspendLayout();
            // 
            // volumeTrackBar
            // 
            this.volumeTrackBar.Location = new System.Drawing.Point(116, 6);
            this.volumeTrackBar.Maximum = 100;
            this.volumeTrackBar.Name = "volumeTrackBar";
            this.volumeTrackBar.Size = new System.Drawing.Size(186, 45);
            this.volumeTrackBar.TabIndex = 0;
            this.volumeTrackBar.ValueChanged += new System.EventHandler(this.volumeTrackBar_ValueChanged);
            // 
            // SettingsBtn
            // 
            this.SettingsBtn.Image = ((System.Drawing.Image)(resources.GetObject("SettingsBtn.Image")));
            this.SettingsBtn.Location = new System.Drawing.Point(301, 6);
            this.SettingsBtn.Name = "SettingsBtn";
            this.SettingsBtn.Size = new System.Drawing.Size(31, 31);
            this.SettingsBtn.TabIndex = 1;
            this.SettingsBtn.UseVisualStyleBackColor = true;
            this.SettingsBtn.Click += new System.EventHandler(this.SettingsBtn_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1264, 716);
            this.Controls.Add(this.SettingsBtn);
            this.Controls.Add(this.volumeTrackBar);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "MainForm";
            this.Text = "YouTube Music";
            this.TransparencyKey = System.Drawing.Color.Wheat;
            ((System.ComponentModel.ISupportInitialize)(this.volumeTrackBar)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TrackBar volumeTrackBar;
        private System.Windows.Forms.Button SettingsBtn;
    }
}

