//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated using a tool
//     Laufzeitversion: 4.0.30319.42000
//
//     Changes made to this file may result in incorrect behavior and will be overwritten whenever
//     the code is generated again
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youtube_Music.Properties
{


    /// <summary>
    ///   A strongly typified resource class to search for localized strings, etc.
    /// </summary>
    // This class was generated automatically by the StronglyTypedResourceBuilder class
    // using a tool like ResGen or Visual Studio
    // To add or remove a member change the .ResX file and execute ResGenUm
    // with the argument /str again or recreate your VS project
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Youtube_Music.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overwrites the CurrentUICulture property for the current thread for all
        ///   resource lookups used by this strongly typied resoure class
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
